---
# defaults file for zabbix-agent

zabbix_version: 2.4
zabbix_repo: True
agent_server: "{{ zabbix_ec2_private_dns_name }}"
agent_serveractive: "{{ zabbix_ec2_private_dns_name}}:10051"

# Zabbix API stuff
zabbix_api_use: True
zabbix_api_user: admin
zabbix_api_pass: zabbix
zabbix_create_hostgroup: present  # or absent
zabbix_create_host: present       # or absent
zabbix_host_status: enabled       # or disabled
zabbix_useuip: 1
zabbix_host_groups:
  - Linux servers
zabbix_link_templates:
  - Template OS Linux
zabbix_macros: 
  - macro_key: key
    macro_value: value

# Zabbix configuration variables
agent_pidfile: /var/run/zabbix/zabbix_agentd.pid
agent_logfile: /var/log/zabbix/zabbix_agentd.log
agent_logfilesize: 100
agent_debuglevel: 3
agent_sourceip:
agent_enableremotecommands: 0
agent_logremotecommands: 0
agent_listenport: 10050
agent_listeninterface: eth0
agent_listenip: 
agent_startagents: 3
agent_hostname: 
agent_hostnameitem: 
agent_hostmetadata:
agent_hostmetadataitem: 
agent_refreshactivechecks: 120
agent_buffersend: 5
agent_buffersize: 100
agent_maxlinespersecond: 100
agent_allowroot: 0
agent_zabbix_alias:
agent_timeout: 3
agent_include: /etc/zabbix/zabbix_agentd.d
agent_unsafeuserparameters: 0
agent_userparameter:
agent_loadmodulepath: ${libdir}/modules
agent_loadmodule:
