---

- name: Install packages need to deploy django projects
  apt: name={{ item }} state=present
  with_items: pkgs

- name: Copy uwsgi configuration file to remote server
  template: src=itcook.ini.j2 dest=/etc/uwsgi/apps-available/itcook.ini

- name: Activate via link uwsgi configuration copied early
  file: src=/etc/uwsgi/apps-available/itcook.ini dest=/etc/uwsgi/apps-enabled/itcook.ini owner=root group=root state=link

- name: Enable autostart of uwsgi application server
  service: name=uwsgi state=running enabled=yes
