---

- name: Install mysql package to remote server
  apt: name={{ item }} state=present
  with_items: pkgs

- name: Copy template of basic configuration
  template: src=my.cnf.j2 dest=/etc/mysql/my.cnf owner=root group=root mode=644

- name: Enable autostart of service and restart it
  service: name=mysql state=running enabled=yes

- name: Copy dump of database to remote system
  synchronize: src=checkout/{{ site_name }}.sql dest=/tmp/{{ site_name }}.sql

- name: Create new database to import data into
  mysql_db: name={{ site_name }} state=present

- name: Import database from tmp folder to mysql server
  mysql_db: name={{ site_name }} state=import target=/tmp/{{ site_name }}.sql

- name: Removes all anonymous user accounts
  mysql_user: name='' host=localhost state=absent