---

- name: Install the nginx packages
  apt: name={{ item }} state=present update_cache=yes
  with_items: pkgs
  when: ansible_os_family == "Debian"

- name: Copy main configuration file to server
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf owner=root group=root mode=644

- name: Copy site related configuration file
  template: src=default.j2 dest=/etc/nginx/sites-available/default

- name: Activate the configuration of newly copied site
  file: src=/etc/nginx/sites-available/default dest=/etc/nginx/sites-enabled/default owner=root group=root state=link

- name: Enable autostart of nginx
  service: name=nginx state=running enabled=yes

