---

- name: Update all packages to latest
  yum: name=* state=latest

- name: disable iptables
  shell: systemctl disable firewalld

- name: stop iptables
  service: name=firewalld state=stopped

- name: Install the packages
  yum: name={{ item }} state=present
  with_items: redhat_pkg
  when: ansible_os_family == "RedHat"

- name: setup timezone link
  shell: "timedatectl set-timezone {{ site_timezone_area }}/{{ site_timezone_city }}"